# Generated by Django 2.2.7 on 2021-08-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('Roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=20)),
                ('School', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=14)),
                ('Address', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'StudentInfo',
            },
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('studentinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appone.StudentInfo')),
                ('Maths', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('Biology', models.IntegerField()),
                ('English', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentAcademics',
            },
            bases=('appone.studentinfo',),
        ),
    ]
